### PR TITLE
Added registration

### PR DESCRIPTION
**Pull request by mexehamy**
I've tried to add registration for users in my blog, using this app(https://github.com/macropin/django-registration).

Due to this I'm having some troubles. This app provides account activation, but as we using Heroku, during our developing process, it will be uncomfortably to activate our account each time we run our blog. But I can't turn the activation off, even when I'm pushing (AUTH_USER_EMAIL_UNIQUE = False) in settings, anyway when I'm trying to login it says "Эта учетная запись отключена.".

@voroninman can u help me with this please ?

### CODE REVIEW

**Comment by mexehamy** [comment]
To register account u should visit this url: $/accounts/register
To login: $/accounts/login/

**Comment by voroninman** [comment]
@mexehamy Sure. I'll take a look today. I'm glad we have a PR to discuss! :+1:

**Comment by voroninman** [comment]
But before I'll look closer you may delete https://github.com/macropin/django-registration files from our repo and try to add it as a dependency via `requirements.txt` file.

**Comment by mexehamy** [comment]
@voroninman yep, deleted it. How should I add it to requirements ?

**Comment by voroninman** [comment]
Try something like `pip install django-authorization` and then `pip freeze
> requirements.txt`. I'm not sure about spelling.

**Comment by mexehamy** [comment]
I've got some troubles with pip or other ways to install apps, because of errors with my ubuntu 14.10, so using it manually mostly. 

I've added this app to requirements manually.

In few days planning to change my OS on 14.04, because my 14.10 seems to be dead because it sends endless errors everyday.
screenshot from 2015-11-15 21 14 28

**Comment by voroninman** [comment]
To avoid this kind of errors I suggest to use `pyenv`. Try to `pip` when the virtualenv is activated.

The error above is not related to Ubuntu.

**Comment by voroninman** [comment]
I've got the answer to your initial question in the PR description. 

In this case we need to use https://docs.djangoproject.com/en/1.8/ref/django-admin/#what-s-a-fixture .

**Pull request closed without merging**
